# Generated by Django 5.2.3 on 2025-07-13 03:45

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Nombre de contacto de emergencia",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[+]?[0-9]+$", "Ingrese un número válido"
                    )
                ],
                verbose_name="Teléfono de contacto de emergencia",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="identification_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]+$", "Solo se permiten números"
                    )
                ],
                verbose_name="Número de identificación",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="dni",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]+$", "Solo se permiten números"
                    )
                ],
                verbose_name="DNI",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="emergency_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[+]?[0-9]+$", "Ingrese un número válido"
                    )
                ],
                verbose_name="Teléfono de emergencia",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                max_length=1,
                verbose_name="Género",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[+]?[0-9]+$", "Ingrese un número válido"
                    )
                ],
                verbose_name="Teléfono",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=uuid.uuid4, max_length=150, unique=True),
        ),
    ]
