# Generated by Django 5.2.3 on 2025-07-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0003_user_date_of_birth_user_emergency_contact_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
