# Generated by Django 5.2.3 on 2025-07-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_tokens",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Tokens de respaldo"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA Habilitado"),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_secret",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Secreto 2FA"
            ),
        ),
    ]
