# Generated by Django 5.2.3 on 2025-07-19 08:23

import authentication.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_backup_tokens_user_two_factor_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dni",
            field=authentication.fields.EncryptedCharField(
                blank=True,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]+$", "Solo se permiten números"
                    )
                ],
                verbose_name="DNI",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="identification_number",
            field=authentication.fields.EncryptedCharField(
                blank=True,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]+$", "Solo se permiten números"
                    )
                ],
                verbose_name="Número de identificación",
            ),
        ),
    ]
