# Generated by Django 5.2.3 on 2025-07-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_add_emergency_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Paciente"),
                    ("doctor", "Doctor"),
                    ("nurse", "Enfermero/a"),
                    ("receptionist", "Recepcionista"),
                    ("admin", "Administrador"),
                    ("pharmacist", "Farmaceutico"),
                    ("emergency", "Personal de Emergencias"),
                    ("obstetriz", "Obstetriz"),
                    ("odontologo", "Odontólogo"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
    ]
