# Generated by Django 5.2.3 on 2025-07-10 03:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("appointments", "Reporte de Citas"),
                            ("patients", "Reporte de Pacientes"),
                            ("medications", "Reporte de Medicamentos"),
                            ("financial", "Reporte Financiero"),
                            ("emergency", "Reporte de Emergencias"),
                            ("occupancy", "Reporte de Ocupación"),
                            ("lab_tests", "Reporte de Exámenes"),
                            ("custom", "Reporte Personalizado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "query_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuración de consultas SQL o filtros",
                    ),
                ),
                (
                    "columns_config",
                    models.JSONField(
                        default=list, help_text="Configuración de columnas a mostrar"
                    ),
                ),
                (
                    "filters_config",
                    models.JSONField(
                        default=dict, help_text="Filtros disponibles para el reporte"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Reporte",
                "verbose_name_plural": "Plantillas de Reportes",
                "ordering": ["report_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("appointments", "Reporte de Citas"),
                            ("patients", "Reporte de Pacientes"),
                            ("medications", "Reporte de Medicamentos"),
                            ("financial", "Reporte Financiero"),
                            ("emergency", "Reporte de Emergencias"),
                            ("occupancy", "Reporte de Ocupación"),
                            ("lab_tests", "Reporte de Exámenes"),
                            ("custom", "Reporte Personalizado"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Parámetros utilizados para generar el reporte",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "xlsx", "csv", "json"]
                            )
                        ],
                    ),
                ),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("row_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "generation_time",
                    models.FloatField(
                        blank=True,
                        help_text="Tiempo de generación en segundos",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de expiración del archivo",
                        null=True,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Generado",
                "verbose_name_plural": "Reportes Generados",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("yearly", "Anual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        default="08:00",
                        help_text="Hora del día para generar el reporte",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        help_text="Para reportes semanales",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Para reportes mensuales (1-31)",
                        null=True,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list, help_text="Lista de emails para enviar el reporte"
                    ),
                ),
                (
                    "include_in_email",
                    models.BooleanField(
                        default=True,
                        help_text="Incluir el reporte como adjunto en el email",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_reports",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Programado",
                "verbose_name_plural": "Reportes Programados",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("generated", "Generado"),
                            ("viewed", "Visto"),
                            ("downloaded", "Descargado"),
                            ("emailed", "Enviado por Email"),
                            ("deleted", "Eliminado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Información adicional sobre la acción"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="reports.generatedreport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría de Reporte",
                "verbose_name_plural": "Auditorías de Reportes",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["report", "timestamp"],
                        name="reports_rep_report__51feb4_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="reports_rep_user_id_d18dbd_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["status", "created_at"], name="reports_gen_status_cacdbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["report_type", "created_at"],
                name="reports_gen_report__97610f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["generated_by", "created_at"],
                name="reports_gen_generat_4abf6c_idx",
            ),
        ),
    ]
