# Generated by Django 5.2.3 on 2025-07-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("request_body", models.TextField(blank=True)),
                ("response_status", models.IntegerField()),
                ("response_time_ms", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log de Acceso API",
                "verbose_name_plural": "Logs de Acceso API",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="APIRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("hour", models.IntegerField()),
                ("minute", models.IntegerField()),
                ("request_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Límite de Tasa API",
                "verbose_name_plural": "Límites de Tasa API",
            },
        ),
        migrations.CreateModel(
            name="APIWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("appointment.created", "Cita Creada"),
                            ("appointment.updated", "Cita Actualizada"),
                            ("appointment.cancelled", "Cita Cancelada"),
                            ("patient.created", "Paciente Creado"),
                            ("patient.updated", "Paciente Actualizado"),
                            ("prescription.created", "Receta Creada"),
                            ("lab_result.ready", "Resultado de Lab Listo"),
                            ("emergency.admission", "Admisión de Emergencia"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "secret",
                    models.CharField(
                        help_text="Secret para validar requests", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Webhook API",
                "verbose_name_plural": "Webhooks API",
            },
        ),
        migrations.CreateModel(
            name="ExternalAPIClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre del cliente"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "api_key",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="API Key"
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(max_length=128, verbose_name="API Secret"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "can_read_patients",
                    models.BooleanField(
                        default=False, verbose_name="Puede leer pacientes"
                    ),
                ),
                (
                    "can_write_patients",
                    models.BooleanField(
                        default=False, verbose_name="Puede escribir pacientes"
                    ),
                ),
                (
                    "can_read_appointments",
                    models.BooleanField(default=False, verbose_name="Puede leer citas"),
                ),
                (
                    "can_write_appointments",
                    models.BooleanField(
                        default=False, verbose_name="Puede escribir citas"
                    ),
                ),
                (
                    "can_read_medical_records",
                    models.BooleanField(
                        default=False, verbose_name="Puede leer expedientes"
                    ),
                ),
                (
                    "can_write_medical_records",
                    models.BooleanField(
                        default=False, verbose_name="Puede escribir expedientes"
                    ),
                ),
                (
                    "can_read_pharmacy",
                    models.BooleanField(
                        default=False, verbose_name="Puede leer farmacia"
                    ),
                ),
                (
                    "can_write_pharmacy",
                    models.BooleanField(
                        default=False, verbose_name="Puede escribir farmacia"
                    ),
                ),
                (
                    "daily_request_limit",
                    models.IntegerField(
                        default=10000, verbose_name="Límite diario de peticiones"
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.IntegerField(default=60, verbose_name="Límite por minuto"),
                ),
            ],
            options={
                "verbose_name": "Cliente API Externa",
                "verbose_name_plural": "Clientes API Externa",
            },
        ),
    ]
