# Generated by Django 5.2.3 on 2025-07-09 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_external", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="externalapiclient",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiwebhook",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhooks",
                to="api_external.externalapiclient",
            ),
        ),
        migrations.AddField(
            model_name="apiratelimit",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_limits",
                to="api_external.externalapiclient",
            ),
        ),
        migrations.AddField(
            model_name="apiaccesslog",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="api_external.externalapiclient",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apiwebhook",
            unique_together={("client", "event", "url")},
        ),
        migrations.AlterUniqueTogether(
            name="apiratelimit",
            unique_together={("client", "date", "hour", "minute")},
        ),
    ]
