# Generated by Django 5.2.3 on 2025-07-10 20:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appointment",
            name="appointment_appoint_c5b816_idx",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="appointment_patient_44acdc_idx",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="appointment_doctor__4d4b79_idx",
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("doctor", "appointment_date", "appointment_time")},
        ),
        migrations.AddField(
            model_name="medicalschedule",
            name="specialty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="appointments.specialty",
                verbose_name="Especialidad",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateField(verbose_name="Fecha de cita"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="ID de cita",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.TimeField(verbose_name="Hora de cita"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="Motivo de cancelación"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelado en"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="duration",
            field=models.IntegerField(
                default=30,
                help_text="Duración en minutos",
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="Duración",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Notas adicionales", verbose_name="Notas"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="reason",
            field=models.TextField(
                help_text="Motivo de la consulta", verbose_name="Motivo"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="appointments.specialty",
                verbose_name="Especialidad",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Agendada"),
                    ("confirmed", "Confirmada"),
                    ("in_progress", "En Progreso"),
                    ("completed", "Completada"),
                    ("cancelled", "Cancelada"),
                    ("no_show", "No Asistió"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreminder",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="appointments.appointment",
                verbose_name="Cita",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreminder",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Mensaje de error"),
        ),
        migrations.AlterField(
            model_name="appointmentreminder",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="Enviado"),
        ),
        migrations.AlterField(
            model_name="appointmentreminder",
            name="reminder_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("push", "Push Notification"),
                ],
                max_length=10,
                verbose_name="Tipo de recordatorio",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreminder",
            name="scheduled_for",
            field=models.DateTimeField(verbose_name="Programado para"),
        ),
        migrations.AlterField(
            model_name="appointmentreminder",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Enviado en"
            ),
        ),
        migrations.AlterField(
            model_name="medicalschedule",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="medicalschedule",
            name="end_time",
            field=models.TimeField(verbose_name="Hora de fin"),
        ),
        migrations.AlterField(
            model_name="medicalschedule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="medicalschedule",
            name="slot_duration",
            field=models.IntegerField(
                default=30,
                help_text="Duración de cada cita en minutos",
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="Duración de cita",
            ),
        ),
        migrations.AlterField(
            model_name="medicalschedule",
            name="start_time",
            field=models.TimeField(verbose_name="Hora de inicio"),
        ),
        migrations.AlterField(
            model_name="medicalschedule",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (0, "Lunes"),
                    (1, "Martes"),
                    (2, "Miércoles"),
                    (3, "Jueves"),
                    (4, "Viernes"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                verbose_name="Día de la semana",
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="cancelled_by",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="created_by",
        ),
    ]
