# Generated by Django 5.2.3 on 2025-07-10 20:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_type",
                    models.CharField(
                        choices=[
                            ("medication", "Medicación"),
                            ("procedure", "Procedimiento"),
                            ("surgery", "Cirugía"),
                            ("observation", "Observación"),
                            ("supportive", "Cuidados de soporte"),
                            ("diagnostic", "Diagnóstico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("treatment_name", models.CharField(max_length=200)),
                ("treatment_code", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField()),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("successful", "Exitoso"),
                            ("partial", "Parcialmente exitoso"),
                            ("failed", "Fallido"),
                            ("ongoing", "En curso"),
                            ("discontinued", "Descontinuado"),
                        ],
                        default="ongoing",
                        max_length=50,
                    ),
                ),
                ("complications", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "resources_used",
                    models.TextField(
                        blank=True, help_text="Equipos o materiales utilizados"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "assisted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="emergency_treatments_assisted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emergency_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="emergency.emergencycase",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_treatments_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratamiento de Emergencia",
                "verbose_name_plural": "Tratamientos de Emergencia",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["treatment_type", "started_at"],
                        name="emergency_e_treatme_00b6d3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TriageAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "triage_level",
                    models.IntegerField(
                        choices=[
                            (1, "Resucitación - Riesgo vital inmediato"),
                            (2, "Emergencia - Riesgo vital potencial"),
                            (3, "Urgencia - Situación urgente"),
                            (4, "Menos urgente - Situación menos urgente"),
                            (5, "No urgente - Situación no urgente"),
                        ]
                    ),
                ),
                ("chief_complaint", models.TextField()),
                ("vital_signs_summary", models.TextField()),
                (
                    "pain_assessment",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("airway_compromised", models.BooleanField(default=False)),
                ("breathing_difficulty", models.BooleanField(default=False)),
                ("circulation_problem", models.BooleanField(default=False)),
                ("neurological_deficit", models.BooleanField(default=False)),
                ("high_risk_mechanism", models.BooleanField(default=False)),
                ("assessment_duration", models.DurationField(blank=True, null=True)),
                ("clinical_notes", models.TextField(blank=True)),
                ("immediate_interventions", models.TextField(blank=True)),
                (
                    "emergency_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_assessments",
                        to="emergency.emergencycase",
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        limit_choices_to={"role": "nurse"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triage_assessments_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de Triaje",
                "verbose_name_plural": "Evaluaciones de Triaje",
                "ordering": ["-assessment_time"],
                "indexes": [
                    models.Index(
                        fields=["assessment_time", "triage_level"],
                        name="emergency_t_assessm_cbf9f9_idx",
                    )
                ],
            },
        ),
    ]
