# Generated by Django 5.2.3 on 2025-07-09 07:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoría de Medicamento",
                "verbose_name_plural": "Categorías de Medicamentos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "dosage_form",
                    models.CharField(help_text="Forma farmacéutica", max_length=100),
                ),
                (
                    "strength",
                    models.CharField(help_text="Concentración", max_length=50),
                ),
                ("quantity_in_stock", models.PositiveIntegerField(default=0)),
                (
                    "reordering_threshold",
                    models.PositiveIntegerField(
                        default=10, help_text="Cantidad mínima para reordenar"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="pharmacy_me_name_46a660_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Dispensation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("dispensed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensed_medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pharmacist",
                    models.ForeignKey(
                        limit_choices_to={"role": "pharmacist"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_dispensations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispensations",
                        to="pharmacy.medication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispensación",
                "verbose_name_plural": "Dispensaciones",
                "ordering": ["-dispensed_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100, unique=True)),
                ("quantity", models.PositiveIntegerField()),
                ("manufacturing_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("supplier", models.CharField(max_length=200)),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="pharmacy.medication",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Medicamento",
                "verbose_name_plural": "Lotes de Medicamentos",
                "ordering": ["-received_date"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("inventory", "Inventario"),
                            ("expiry", "Próximos a vencer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "generated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("report_data", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Farmacia",
                "verbose_name_plural": "Reportes de Farmacia",
                "ordering": ["-generated_date"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Entrada"),
                            ("out", "Salida"),
                            ("adjustment", "Ajuste"),
                            ("return", "Devolución"),
                            ("expired", "Vencido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("reason", models.TextField()),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("stock_before", models.IntegerField()),
                ("stock_after", models.IntegerField()),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="pharmacy.medicationbatch",
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="pharmacy.medication",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Stock",
                "verbose_name_plural": "Movimientos de Stock",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="medicationbatch",
            index=models.Index(
                fields=["batch_number"], name="pharmacy_me_batch_n_4d22a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationbatch",
            index=models.Index(
                fields=["expiry_date"], name="pharmacy_me_expiry__266ee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["medication", "performed_at"],
                name="pharmacy_st_medicat_3539e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type"], name="pharmacy_st_movemen_ec6bc6_idx"
            ),
        ),
    ]
