# Generated by Django 5.2.3 on 2025-07-13 03:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("batch_number", models.CharField(max_length=100, unique=True)),
                ("manufacturing_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField()),
                ("supplier", models.CharField(blank=True, max_length=200)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=50)),
                ("minimum_stock", models.PositiveIntegerField(default=10)),
                ("maximum_stock", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_records",
                        to="pharmacy.medication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventarios",
                "ordering": ["medication__name", "expiration_date"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prescription_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("diagnosis", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("dispensed", "Dispensado"),
                            ("partially_dispensed", "Parcialmente Dispensado"),
                            ("cancelled", "Cancelado"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("dispensed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "valid_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Días de validez"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "doctor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_issued_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescripción",
                "verbose_name_plural": "Prescripciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("duration_days", models.PositiveIntegerField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True)),
                ("dispensed", models.BooleanField(default=False)),
                ("dispensed_quantity", models.PositiveIntegerField(default=0)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescription_items",
                        to="pharmacy.medication",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Prescripción",
                "verbose_name_plural": "Items de Prescripción",
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "status"], name="pharmacy_pr_patient_903ab2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["created_at"], name="pharmacy_pr_created_9ee48d_idx"
            ),
        ),
    ]
